#!/usr/bin/env python3
"""Download the site's webfonts from Google Fonts and self-host them.

Run this only when the family or weight list changes:

    python3 scripts/fetch-fonts.py

Writes woff2 files to public/fonts/ and regenerates src/styles/fonts.css.
Self-hosting removes a render-blocking third-party stylesheet and keeps
visitor requests on this origin.
"""
import pathlib
import re
import shutil
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "src" / "styles" / "fonts.css"

# Latin only. The site is English; other subsets are payload no page uses.
KEEP_SUBSETS = {"latin", "latin-ext"}

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400"
    "&family=IBM+Plex+Sans:wght@400;500;600"
    "&family=IBM+Plex+Mono:wght@400;500"
    "&display=swap"
)

# A modern UA is required or Google serves legacy ttf instead of woff2.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)


def fetch(url: str, ua: str = UA) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": ua}), timeout=30
    ).read()


def main() -> None:
    css = fetch(GOOGLE_CSS).decode()
    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*@font-face \{(.*?)\}", css, re.S)

    if FONTS.exists():
        shutil.rmtree(FONTS)
    FONTS.mkdir(parents=True)

    faces = []
    by_url: dict[str, str] = {}

    for subset, body in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", body).group(1)
        style = re.search(r"font-style: (\w+)", body).group(1)
        weight = re.search(r"font-weight: ([\d ]+)", body).group(1).strip()
        url = re.search(r"url\(([^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range: ([^;]+);", body).group(1).strip()

        # Variable fonts serve one file for several weights. Reuse the
        # filename we already wrote rather than pointing at one that
        # was never downloaded.
        if url in by_url:
            filename = by_url[url]
        else:
            slug = family.lower().replace(" ", "-")
            filename = f"{slug}-{weight.replace(' ', '-')}-{style}-{subset}.woff2"
            (FONTS / filename).write_bytes(fetch(url))
            by_url[url] = filename

        faces.append((family, style, weight, filename, urange, subset))

    lines = [
        "/* Self-hosted fonts — generated by scripts/fetch-fonts.py. Do not edit.",
        "",
        "   No third-party stylesheet, nothing render-blocking, and no visitor",
        "   request leaves this origin to load type. Latin subsets only.",
        "",
        "   Variable families serve one file across several weights, so the same",
        "   woff2 legitimately appears under more than one @font-face. */",
        "",
    ]
    for family, style, weight, filename, urange, subset in faces:
        lines += [
            f"/* {family} {weight} {style} — {subset} */",
            "@font-face {",
            f"  font-family: '{family}';",
            f"  font-style: {style};",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url('/fonts/{filename}') format('woff2');",
            f"  unicode-range: {urange};",
            "}",
            "",
        ]
    CSS_OUT.write_text("\n".join(lines))

    total = sum(f.stat().st_size for f in FONTS.iterdir())
    print(f"{len(faces)} faces, {len(by_url)} files, {total / 1024:.0f} KB")


if __name__ == "__main__":
    main()
