#!/usr/bin/env python3
"""Append metric-matched fallback @font-face rules to src/styles/fonts.css.

    python3 scripts/font-fallbacks.py

While a webfont is still downloading the browser paints a system font. If that
stand-in has different metrics the page moves when the real font arrives, which
is layout shift the reader sees as a flicker. These rules size the stand-in to
match, so the swap is invisible.

Metrics come from each family's own font tables. Google Fonts serves TTF to a
user agent that does not advertise woff2, which avoids needing a Brotli decoder
locally; the files are read and discarded.

Run after scripts/fetch-fonts.py.
"""
import pathlib
import re
import tempfile
import urllib.request

from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = ROOT / "src" / "styles" / "fonts.css"

# An old Safari UA → Google serves plain TTF, which fontTools reads without
# a Brotli decoder.
LEGACY_UA = "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_5; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Version/5.0.1 Safari/533.17.8"

FAMILIES = {
    "Source Serif 4": "Source+Serif+4",
    "IBM Plex Sans": "IBM+Plex+Sans",
    "IBM Plex Mono": "IBM+Plex+Mono",
}

# The system face each family stands in for, with its published mean lowercase
# advance in em. Measuring locally is unreliable — these must hold on the
# reader's machine, not this one.
FALLBACK = {
    "Source Serif 4": ("Georgia, 'Times New Roman'", 0.5090),
    "IBM Plex Sans": ("Arial, Helvetica", 0.5280),
    "IBM Plex Mono": ("'Courier New', Courier", 0.6000),
}

MARKER = "/* Metric-matched fallbacks"


def metrics(family_param: str) -> tuple[float, float, float, float]:
    css = urllib.request.urlopen(
        urllib.request.Request(
            f"https://fonts.googleapis.com/css?family={family_param}",
            headers={"User-Agent": LEGACY_UA},
        ),
        timeout=30,
    ).read().decode()
    url = re.search(r"url\((https://[^)]+)\)", css).group(1)
    data = urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": LEGACY_UA}), timeout=30
    ).read()

    with tempfile.NamedTemporaryFile(suffix=".ttf") as tmp:
        tmp.write(data)
        tmp.flush()
        font = TTFont(tmp.name)
        upm = font["head"].unitsPerEm
        hhea = font["hhea"]
        cmap, hmtx = font.getBestCmap(), font["hmtx"]
        widths = [
            hmtx[cmap[ord(c)]][0]
            for c in "abcdefghijklmnopqrstuvwxyz"
            if ord(c) in cmap
        ]
        return (
            hhea.ascent / upm * 100,
            abs(hhea.descent) / upm * 100,
            hhea.lineGap / upm * 100,
            sum(widths) / len(widths) / upm,
        )


def main() -> None:
    lines = [
        "",
        MARKER + " — generated by scripts/font-fallbacks.py.",
        "",
        "   While a webfont loads the browser paints one of these instead, sized",
        "   from the webfont's own tables so the swap does not move the page.",
        "   Reference the family as \"'Source Serif 4', 'Source Serif 4 Fallback', Georgia, serif\". */",
        "",
    ]
    for family, param in FAMILIES.items():
        ascent, descent, gap, avg = metrics(param)
        locals_, fallback_avg = FALLBACK[family]
        adjust = avg / fallback_avg * 100
        scale = adjust / 100
        print(
            f"{family:16} ascent={ascent:6.2f}% descent={descent:5.2f}% "
            f"gap={gap:4.2f}% size-adjust={adjust:6.2f}%"
        )
        srcs = ", ".join(f"local({name.strip()})" for name in locals_.split(","))
        lines += [
            "@font-face {",
            f"  font-family: '{family} Fallback';",
            f"  src: {srcs};",
            f"  size-adjust: {adjust:.2f}%;",
            f"  ascent-override: {ascent / scale:.2f}%;",
            f"  descent-override: {descent / scale:.2f}%;",
            f"  line-gap-override: {gap / scale:.2f}%;",
            "}",
            "",
        ]

    current = CSS.read_text()
    if MARKER in current:
        current = current[: current.index(MARKER)].rstrip() + "\n"
    CSS.write_text(current + "\n".join(lines))
    print("\nfallback faces written")


if __name__ == "__main__":
    main()
