// AUTO-GENERATED by the curriculum-architecture workflow (16 tracks).
// Node status = curriculum AVAILABILITY (live = has a page · coming = scheduled).
export type NodeStatus = 'live' | 'curated' | 'coming';
export interface TrackNode { title: string; slug?: string; status: NodeStatus; eta?: string; }
export interface Track { id: string; n: string; name: string; group: string; meta: string; summary: string; nodes: TrackNode[]; }
export interface RoleTrack { id: string; name: string; blurb: string; status: NodeStatus; }

export const groups: string[] = [
  "Foundations",
  "Working with Models",
  "Building",
  "Agentic",
  "Production"
];

export const tracks: Track[] = [
  {
    "id": "maths-foundations",
    "n": "01",
    "name": "Maths Foundations",
    "group": "Foundations",
    "meta": "4 live · 10 coming",
    "summary": "The minimum maths — vectors, probability, and gradients — needed to actually reason about how LLMs compute, not just use them.",
    "nodes": [
      {
        "title": "Vectors: The Basic Unit of Data",
        "status": "live",
        "slug": "what-is-a-vector"
      },
      {
        "title": "The Dot Product, Explained",
        "status": "coming"
      },
      {
        "title": "Cosine Similarity: Measuring How Alike Two Things Are",
        "status": "live",
        "slug": "cosine-similarity"
      },
      {
        "title": "Matrices as Transformations",
        "status": "coming"
      },
      {
        "title": "Probability Basics for AI",
        "status": "coming"
      },
      {
        "title": "The Softmax Function",
        "status": "live",
        "slug": "the-softmax-function"
      },
      {
        "title": "Temperature: Reshaping a Probability Distribution",
        "status": "coming"
      },
      {
        "title": "Logarithms for Machine Learning",
        "status": "coming"
      },
      {
        "title": "Perplexity: How Language Models Are Scored",
        "status": "coming"
      },
      {
        "title": "Gradients: Slopes in Many Dimensions",
        "status": "coming"
      },
      {
        "title": "Gradient Descent, Intuitively",
        "status": "live",
        "slug": "gradient-descent-intuition"
      },
      {
        "title": "Backpropagation: How Networks Assign Blame",
        "status": "coming"
      },
      {
        "title": "Why High-Dimensional Space Feels Weird",
        "status": "coming"
      },
      {
        "title": "The Geometry of Embeddings",
        "status": "coming"
      }
    ]
  },
  {
    "id": "ai-foundations",
    "n": "02",
    "name": "AI Foundations",
    "group": "Foundations",
    "meta": "6 live · 9 coming",
    "summary": "The ground floor of AI: what these systems are, how they learn, and a working mental model of what they can and can't do.",
    "nodes": [
      {
        "title": "How LLMs Work",
        "status": "live",
        "slug": "how-llms-work"
      },
      {
        "title": "Tokens, Context, and Cost",
        "status": "live",
        "slug": "tokens-context-cost"
      },
      {
        "title": "Choosing a Model",
        "status": "live",
        "slug": "choosing-a-model"
      },
      {
        "title": "AI vs. Machine Learning vs. Deep Learning",
        "status": "live",
        "slug": "ai-vs-ml-vs-deep-learning"
      },
      {
        "title": "What a Neural Network Actually Is",
        "status": "live",
        "slug": "what-is-a-neural-network"
      },
      {
        "title": "Narrow AI vs. General AI",
        "status": "coming"
      },
      {
        "title": "Supervised Learning, Explained",
        "status": "coming"
      },
      {
        "title": "Self-Supervised Learning: Training Without Labels",
        "status": "coming"
      },
      {
        "title": "Training vs. Inference",
        "status": "coming"
      },
      {
        "title": "Generalization vs. Overfitting",
        "status": "coming"
      },
      {
        "title": "Foundation Models, Explained",
        "status": "coming"
      },
      {
        "title": "The Data the Model Learned From",
        "status": "coming"
      },
      {
        "title": "AI Benchmarks and What They Miss",
        "status": "coming"
      },
      {
        "title": "A Mental Model for What LLMs Can and Can't Do",
        "status": "live",
        "slug": "what-llms-can-and-cannot-do"
      },
      {
        "title": "AI Agents vs. Chatbots",
        "status": "coming"
      }
    ]
  },
  {
    "id": "llm-foundations",
    "n": "03",
    "name": "LLM Foundations",
    "group": "Foundations",
    "meta": "4 live · 10 coming",
    "summary": "How large language models work under the hood, from tokenization through attention and pretraining to the fine-tuning that makes them useful assistants.",
    "nodes": [
      {
        "title": "Tokenization: How Text Becomes Tokens",
        "status": "live",
        "slug": "tokenization-explained"
      },
      {
        "title": "Embeddings: Turning Tokens Into Geometry",
        "status": "coming"
      },
      {
        "title": "The Attention Mechanism, Explained",
        "status": "live",
        "slug": "attention-mechanism-explained"
      },
      {
        "title": "Positional Encoding: How Transformers Track Order",
        "status": "coming"
      },
      {
        "title": "The Transformer Architecture",
        "status": "live",
        "slug": "the-transformer-architecture"
      },
      {
        "title": "Next-Token Prediction: The One Objective",
        "status": "live",
        "slug": "next-token-prediction"
      },
      {
        "title": "Pretraining: Learning From the Whole Internet",
        "status": "coming"
      },
      {
        "title": "Context Window Mechanics",
        "status": "coming"
      },
      {
        "title": "Sampling: Temperature, Top-k, and Top-p",
        "status": "coming"
      },
      {
        "title": "Instruction Tuning and RLHF",
        "status": "coming"
      },
      {
        "title": "Emergent Abilities in LLMs",
        "status": "coming"
      },
      {
        "title": "Mixture of Experts, Explained",
        "status": "coming"
      },
      {
        "title": "Model Families: Base, Instruct, Chat, Reasoning",
        "status": "coming"
      },
      {
        "title": "Multimodal LLMs, Explained",
        "status": "coming"
      }
    ]
  },
  {
    "id": "prompt-engineering",
    "n": "04",
    "name": "Prompt Engineering",
    "group": "Working with Models",
    "meta": "5 live · 8 coming",
    "summary": "Reliable, repeatable prompting techniques for getting the output you actually want out of a model.",
    "nodes": [
      {
        "title": "Answer-First Prompting",
        "status": "live",
        "slug": "answer-first-prompting"
      },
      {
        "title": "System Prompts vs User Prompts",
        "status": "live",
        "slug": "system-vs-user-prompts"
      },
      {
        "title": "Delimiters: Fencing Off Instructions from Content",
        "status": "live",
        "slug": "delimiters-and-formatting"
      },
      {
        "title": "Role Prompting: What Personas Actually Change",
        "status": "coming"
      },
      {
        "title": "Few-Shot Prompting: Teaching by Example",
        "status": "live",
        "slug": "few-shot-prompting"
      },
      {
        "title": "Zero-Shot vs Few-Shot: When Examples Earn Their Tokens",
        "status": "coming"
      },
      {
        "title": "Chain-of-Thought: Getting the Model to Show Its Work",
        "status": "live",
        "slug": "chain-of-thought-prompting"
      },
      {
        "title": "Decomposition: Splitting One Big Prompt into a Pipeline",
        "status": "coming"
      },
      {
        "title": "Self-Consistency: Voting Across Multiple Reasoning Paths",
        "status": "coming"
      },
      {
        "title": "Why 'Don't Do X' Backfires",
        "status": "coming"
      },
      {
        "title": "Prompt Templates: Building Reusable, Parameterized Prompts",
        "status": "coming"
      },
      {
        "title": "Prompt Anti-Patterns to Stop Doing",
        "status": "coming"
      },
      {
        "title": "Evaluating Prompts Before You Ship Them",
        "status": "coming"
      }
    ]
  },
  {
    "id": "context-engineering",
    "n": "05",
    "name": "Context Engineering",
    "group": "Working with Models",
    "meta": "3 live · 10 coming",
    "summary": "Curating what actually goes into the context window so the model has the right information, in the right order, at the right cost.",
    "nodes": [
      {
        "title": "Context Engineering vs Prompt Engineering",
        "status": "live",
        "slug": "context-engineering-vs-prompting"
      },
      {
        "title": "Relevance Filtering: Deciding What Doesn't Make the Cut",
        "status": "coming"
      },
      {
        "title": "Context Ordering: Why Position Changes What the Model Notices",
        "status": "coming"
      },
      {
        "title": "Retrieval vs Stuffing: Fetch Just-in-Time or Load It All",
        "status": "live",
        "slug": "retrieval-vs-context-stuffing"
      },
      {
        "title": "Token Budgeting: Splitting a Fixed Context Window",
        "status": "coming"
      },
      {
        "title": "Memory vs State: What Persists Across Turns and Sessions",
        "status": "coming"
      },
      {
        "title": "Compaction: Summarizing History to Reclaim Context Space",
        "status": "coming"
      },
      {
        "title": "Sliding Windows: Rolling Off Old Turns Without Losing the Thread",
        "status": "coming"
      },
      {
        "title": "Context Rot: When More Tokens Make the Model Worse",
        "status": "live",
        "slug": "context-rot"
      },
      {
        "title": "Structuring Injected Context So the Model Can Actually Use It",
        "status": "coming"
      },
      {
        "title": "Merging Context from Multiple Tools Without Contradictions",
        "status": "coming"
      },
      {
        "title": "Long-Context Strategies for Million-Token Windows",
        "status": "coming"
      },
      {
        "title": "Testing Whether More Context Actually Helps",
        "status": "coming"
      }
    ]
  },
  {
    "id": "structured-outputs",
    "n": "06",
    "name": "Structured Outputs",
    "group": "Working with Models",
    "meta": "3 live · 9 coming",
    "summary": "Getting models to return machine-parseable, schema-valid data instead of free text.",
    "nodes": [
      {
        "title": "Why Structured Output: Free Text vs Machine-Parseable Data",
        "status": "live",
        "slug": "why-structured-output"
      },
      {
        "title": "JSON Mode: Forcing Valid JSON Out of the Model",
        "status": "coming"
      },
      {
        "title": "JSON Schema: Specifying Your Exact Data Contract",
        "status": "live",
        "slug": "json-schema-for-outputs"
      },
      {
        "title": "Enums: Locking a Field to a Fixed Set of Values",
        "status": "coming"
      },
      {
        "title": "Nested Objects and Arrays in Output Schemas",
        "status": "coming"
      },
      {
        "title": "Tool Schemas as a Structured-Extraction Mechanism",
        "status": "coming"
      },
      {
        "title": "Pydantic and Zod: Deriving Schemas from Code",
        "status": "coming"
      },
      {
        "title": "Schema Design Choices That Reduce Model Errors",
        "status": "coming"
      },
      {
        "title": "Constrained Decoding: How Guaranteed-Valid Output Actually Works",
        "status": "coming"
      },
      {
        "title": "Validation and Auto-Repair: Catching and Fixing Bad Output",
        "status": "live",
        "slug": "validation-and-auto-repair"
      },
      {
        "title": "Streaming Structured Output: Parsing Before the Response Finishes",
        "status": "coming"
      },
      {
        "title": "Structured Output Failure Modes and How to Spot Them",
        "status": "coming"
      }
    ]
  },
  {
    "id": "hallucinations",
    "n": "07",
    "name": "Hallucinations & Reliability",
    "group": "Working with Models",
    "meta": "3 live · 10 coming",
    "summary": "Understanding why models fabricate, and the concrete techniques to ground, verify, and contain it.",
    "nodes": [
      {
        "title": "What a Hallucination Actually Is",
        "status": "coming"
      },
      {
        "title": "Why Models Hallucinate: The Mechanics Behind Confident Wrong Answers",
        "status": "live",
        "slug": "why-models-hallucinate"
      },
      {
        "title": "Hallucination Risk Factors: Which Tasks Are Most Dangerous",
        "status": "coming"
      },
      {
        "title": "Leading Questions and False Premises That Induce Hallucination",
        "status": "coming"
      },
      {
        "title": "Grounding: Constraining Answers to Supplied Sources",
        "status": "live",
        "slug": "grounding-with-source-documents"
      },
      {
        "title": "RAG as Hallucination Mitigation",
        "status": "coming"
      },
      {
        "title": "Citations: Making Every Claim Traceable to a Source",
        "status": "coming"
      },
      {
        "title": "Teaching a Model to Say 'I Don't Know'",
        "status": "live",
        "slug": "teaching-models-to-say-i-dont-know"
      },
      {
        "title": "Self-Verification: Having the Model Check Its Own Work",
        "status": "coming"
      },
      {
        "title": "Confidence Signals: What Model Certainty Actually Reflects",
        "status": "coming"
      },
      {
        "title": "Fact-Checking Pipelines Before Output Ships",
        "status": "coming"
      },
      {
        "title": "Guardrails for High-Stakes Output",
        "status": "coming"
      },
      {
        "title": "Measuring Hallucination Rate Instead of Spot-Checking",
        "status": "coming"
      }
    ]
  },
  {
    "id": "genai-app-dev",
    "n": "08",
    "name": "GenAI App Dev",
    "group": "Building",
    "meta": "4 live · 10 coming",
    "summary": "Turn a working prompt into a shipped product: streaming UX, cost and latency budgets, and the plumbing that keeps a GenAI feature alive in production.",
    "nodes": [
      {
        "title": "Anatomy of a GenAI Feature",
        "status": "live",
        "slug": "anatomy-of-a-genai-feature"
      },
      {
        "title": "Your First LLM API Call",
        "status": "coming"
      },
      {
        "title": "Streaming Responses to the UI",
        "status": "live",
        "slug": "streaming-responses-to-the-ui"
      },
      {
        "title": "Designing Chat UX That Doesn't Feel Broken",
        "status": "coming"
      },
      {
        "title": "Trimming Conversation History for Context Limits",
        "status": "coming"
      },
      {
        "title": "Prompt Caching for Speed and Cost",
        "status": "coming"
      },
      {
        "title": "Setting Latency Budgets for LLM Features",
        "status": "coming"
      },
      {
        "title": "Cost Budgets and Usage Tracking",
        "status": "coming"
      },
      {
        "title": "Rate Limits and Retry Strategies",
        "status": "live",
        "slug": "rate-limits-and-retry-strategies"
      },
      {
        "title": "Building a Provider Abstraction Layer",
        "status": "coming"
      },
      {
        "title": "Handling API Keys and Secrets Safely",
        "status": "coming"
      },
      {
        "title": "Error Handling for LLM Calls",
        "status": "coming"
      },
      {
        "title": "Guardrails and Input Validation",
        "status": "coming"
      },
      {
        "title": "Shipping Your First End-to-End GenAI App",
        "status": "live",
        "slug": "shipping-your-first-end-to-end-app"
      }
    ]
  },
  {
    "id": "rag",
    "n": "09",
    "name": "RAG",
    "group": "Building",
    "meta": "4 live · 9 coming",
    "summary": "Ground model answers in your own data — from chunking and embeddings through hybrid retrieval, reranking, and knowing when to skip RAG entirely.",
    "nodes": [
      {
        "title": "What Is RAG and When to Use It",
        "status": "live",
        "slug": "what-is-rag-and-when-to-use-it"
      },
      {
        "title": "Chunking Strategies for Documents",
        "status": "live",
        "slug": "chunking-strategies-for-documents"
      },
      {
        "title": "Embeddings and Semantic Similarity",
        "status": "live",
        "slug": "embeddings-and-semantic-similarity"
      },
      {
        "title": "Similarity Search and ANN Indexes",
        "status": "coming"
      },
      {
        "title": "Choosing a Vector Database",
        "status": "coming"
      },
      {
        "title": "Metadata Filtering in Retrieval",
        "status": "coming"
      },
      {
        "title": "Hybrid Search: Lexical and Vector Combined",
        "status": "coming"
      },
      {
        "title": "Query Rewriting and Expansion",
        "status": "coming"
      },
      {
        "title": "Reranking Retrieved Results",
        "status": "coming"
      },
      {
        "title": "Grounding Answers with Citations",
        "status": "coming"
      },
      {
        "title": "Building a RAG Pipeline End to End",
        "status": "coming"
      },
      {
        "title": "Evaluating RAG Quality",
        "status": "live",
        "slug": "evaluating-rag-quality"
      },
      {
        "title": "When RAG Is the Wrong Tool",
        "status": "coming"
      }
    ]
  },
  {
    "id": "tools-function-calling",
    "n": "10",
    "name": "Tools & Function Calling",
    "group": "Building",
    "meta": "3 live · 10 coming",
    "summary": "Give a model hands: design tool schemas it can call correctly, execute them safely, and handle the ways tool calling breaks.",
    "nodes": [
      {
        "title": "What Is Tool Calling",
        "status": "live",
        "slug": "what-is-tool-calling"
      },
      {
        "title": "Designing a Tool Schema",
        "status": "live",
        "slug": "designing-a-tool-schema"
      },
      {
        "title": "Writing Tool Descriptions Models Actually Follow",
        "status": "live",
        "slug": "writing-tool-descriptions-models-follow"
      },
      {
        "title": "Tool Choice and Forcing Tool Use",
        "status": "coming"
      },
      {
        "title": "Executing Tool Calls Safely",
        "status": "coming"
      },
      {
        "title": "Sandboxing Tool Execution",
        "status": "coming"
      },
      {
        "title": "Returning Tool Results to the Model",
        "status": "coming"
      },
      {
        "title": "Handling Tool Errors and Retries",
        "status": "coming"
      },
      {
        "title": "Parallel Tool Calls",
        "status": "coming"
      },
      {
        "title": "Sequential, Multi-Step Tool Use",
        "status": "coming"
      },
      {
        "title": "Structured Output vs. Tool Calls",
        "status": "coming"
      },
      {
        "title": "Common Tool-Calling Failure Modes",
        "status": "coming"
      },
      {
        "title": "Testing and Debugging Tool Calls",
        "status": "coming"
      }
    ]
  },
  {
    "id": "mcp",
    "n": "11",
    "name": "MCP",
    "group": "Building",
    "meta": "6 live · 10 coming",
    "summary": "The protocol that lets any AI app plug into any tool or data source: servers, primitives, transports, auth, and running MCP in production.",
    "nodes": [
      {
        "title": "What Is MCP",
        "status": "live",
        "slug": "what-is-mcp"
      },
      {
        "title": "Your First MCP Server",
        "status": "live",
        "slug": "first-mcp-server"
      },
      {
        "title": "MCP Architecture: Hosts, Clients, Servers",
        "status": "live",
        "slug": "mcp-architecture-hosts-clients-servers"
      },
      {
        "title": "MCP Tools, Resources, and Prompts",
        "status": "live",
        "slug": "mcp-tools-resources-and-prompts"
      },
      {
        "title": "MCP Transports: stdio vs. HTTP",
        "status": "coming"
      },
      {
        "title": "Connecting a Client to an MCP Server",
        "status": "coming"
      },
      {
        "title": "MCP Tool Discovery and Schemas",
        "status": "coming"
      },
      {
        "title": "MCP and the Context Window",
        "status": "live",
        "slug": "mcp-context-window"
      },
      {
        "title": "MCP Auth Fundamentals",
        "status": "coming"
      },
      {
        "title": "The Agent That Dies Overnight: OAuth",
        "status": "live",
        "slug": "agent-dies-overnight-oauth"
      },
      {
        "title": "Securing MCP Servers Against Prompt Injection",
        "status": "coming"
      },
      {
        "title": "Inspecting and Testing MCP Servers",
        "status": "coming"
      },
      {
        "title": "MCP Registries and Discovery",
        "status": "coming"
      },
      {
        "title": "Versioning MCP Servers Without Breaking Clients",
        "status": "coming"
      },
      {
        "title": "Running MCP Servers in Production",
        "status": "coming"
      },
      {
        "title": "Debugging Common MCP Failures",
        "status": "coming"
      }
    ]
  },
  {
    "id": "agentic-ai",
    "n": "12",
    "name": "Agentic AI",
    "group": "Agentic",
    "meta": "4 live · 10 coming",
    "summary": "What an agent actually is, the loop that makes one work, and when to reach for one instead of a plain prompt or workflow.",
    "nodes": [
      {
        "title": "What Makes Something an Agent",
        "status": "live",
        "slug": "what-is-an-agent"
      },
      {
        "title": "The Agent Loop: Sense, Think, Act",
        "status": "live",
        "slug": "the-agent-loop"
      },
      {
        "title": "Giving Agents Tools",
        "status": "coming"
      },
      {
        "title": "ReAct: Interleaving Reasoning and Acting",
        "status": "live",
        "slug": "react-pattern"
      },
      {
        "title": "Planning Before Acting",
        "status": "coming"
      },
      {
        "title": "Short-Term vs Long-Term Memory",
        "status": "coming"
      },
      {
        "title": "Reflection: Letting an Agent Grade Itself",
        "status": "coming"
      },
      {
        "title": "Recovering When Tools Fail",
        "status": "coming"
      },
      {
        "title": "Multi-Agent Patterns: Orchestrator, Pipeline, Debate",
        "status": "coming"
      },
      {
        "title": "Choosing an Orchestration Framework",
        "status": "coming"
      },
      {
        "title": "Setting the Autonomy Dial",
        "status": "coming"
      },
      {
        "title": "When a Workflow Beats an Agent",
        "status": "live",
        "slug": "when-not-to-use-an-agent"
      },
      {
        "title": "Diagnosing Agent Failure Modes",
        "status": "coming"
      },
      {
        "title": "Reading an Agent's Trace",
        "status": "coming"
      }
    ]
  },
  {
    "id": "harness-design",
    "n": "13",
    "name": "Harness Design",
    "group": "Agentic",
    "meta": "4 live · 10 coming",
    "summary": "The engineering scaffold — control loop, tool routing, policy, sandboxing, state — that turns a raw model into a working, controllable agent.",
    "nodes": [
      {
        "title": "The Harness: Everything Around the Model",
        "status": "live",
        "slug": "what-is-a-harness"
      },
      {
        "title": "Building the Control Loop",
        "status": "live",
        "slug": "the-control-loop"
      },
      {
        "title": "Routing Tool Calls to Real Code",
        "status": "coming"
      },
      {
        "title": "Composing the System Prompt at Runtime",
        "status": "coming"
      },
      {
        "title": "Deny-Floors: Rules No Prompt Can Override",
        "status": "live",
        "slug": "deny-floors-and-policy-layers"
      },
      {
        "title": "Allow/Ask/Deny: Designing Approval Gates",
        "status": "live",
        "slug": "permission-and-approval-systems"
      },
      {
        "title": "Running Agents Headless from a Terminal",
        "status": "coming"
      },
      {
        "title": "Sandboxing Tool Execution in a Harness",
        "status": "coming"
      },
      {
        "title": "Checkpointing Long-Running Agent State",
        "status": "coming"
      },
      {
        "title": "Streaming Tokens and Tool Events",
        "status": "coming"
      },
      {
        "title": "Guardrails as Code, Not Prose",
        "status": "coming"
      },
      {
        "title": "Managing Context Inside a Long Session",
        "status": "coming"
      },
      {
        "title": "Delegating Work to Subagents",
        "status": "coming"
      },
      {
        "title": "Logging Every Step for Debuggability",
        "status": "coming"
      }
    ]
  },
  {
    "id": "evals-red-teaming",
    "n": "14",
    "name": "Evals & Red-teaming",
    "group": "Agentic",
    "meta": "3 live · 11 coming",
    "summary": "How to measure whether your agent actually works, and how to break it before an attacker does.",
    "nodes": [
      {
        "title": "Why Vibes-Based Iteration Breaks Down",
        "status": "live",
        "slug": "why-evals-matter"
      },
      {
        "title": "Building a Golden Dataset",
        "status": "live",
        "slug": "building-a-golden-dataset"
      },
      {
        "title": "Offline Evals vs Production Monitoring",
        "status": "coming"
      },
      {
        "title": "Choosing Metrics That Actually Measure Success",
        "status": "coming"
      },
      {
        "title": "LLM-as-Judge: Grading Outputs with a Model",
        "status": "coming"
      },
      {
        "title": "Turning Bugs into a Regression Suite",
        "status": "coming"
      },
      {
        "title": "Designing a Human Review Workflow",
        "status": "coming"
      },
      {
        "title": "Shipping Changes by Eval Diff",
        "status": "coming"
      },
      {
        "title": "Prompt Injection: When Content Becomes Instructions",
        "status": "live",
        "slug": "prompt-injection-basics"
      },
      {
        "title": "Common Jailbreak Techniques and Their Defenses",
        "status": "coming"
      },
      {
        "title": "Testing for Scope Escape",
        "status": "coming"
      },
      {
        "title": "Running a Structured Red-Team Exercise",
        "status": "coming"
      },
      {
        "title": "Automating Adversarial Probes",
        "status": "coming"
      },
      {
        "title": "Tracking Eval Scores Across Model Versions",
        "status": "coming"
      }
    ]
  },
  {
    "id": "production",
    "n": "15",
    "name": "Production & Ops",
    "group": "Production",
    "meta": "3 live · 11 coming",
    "summary": "Run AI features like real infrastructure: observe every call, control the bill, and know exactly what to do the moment something breaks.",
    "nodes": [
      {
        "title": "Log Every LLM Call as Structured Data",
        "status": "live",
        "slug": "structured-logging-for-llm-calls"
      },
      {
        "title": "Redact PII Before It Hits Your Logs",
        "status": "coming"
      },
      {
        "title": "Track Cost Per Request and Per User",
        "status": "live",
        "slug": "token-and-cost-tracking"
      },
      {
        "title": "Cache Prompts and Responses to Cut Cost",
        "status": "coming"
      },
      {
        "title": "Trace Multi-Step Agent and RAG Pipelines",
        "status": "coming"
      },
      {
        "title": "Catch Regressions with Evals in CI",
        "status": "coming"
      },
      {
        "title": "Set SLOs for Latency, Cost, and Quality",
        "status": "coming"
      },
      {
        "title": "Rate-Limit and Add Backpressure to LLM Traffic",
        "status": "coming"
      },
      {
        "title": "Canary and Shadow-Test Prompt or Model Changes",
        "status": "coming"
      },
      {
        "title": "Put a Kill Switch on Every AI Feature",
        "status": "live",
        "slug": "feature-flags-and-kill-switches"
      },
      {
        "title": "Write an On-Call Playbook for AI Failures",
        "status": "coming"
      },
      {
        "title": "Run a Postmortem After a Model Incident",
        "status": "coming"
      },
      {
        "title": "Set a Data Retention Policy for AI Systems",
        "status": "coming"
      },
      {
        "title": "Monitor Production Traffic for Prompt Injection and Abuse",
        "status": "coming"
      }
    ]
  },
  {
    "id": "fine-tuning",
    "n": "16",
    "name": "Fine-tuning & Optimization",
    "group": "Production",
    "meta": "3 live · 11 coming",
    "summary": "Know when specializing a model beats a better prompt, then fine-tune, shrink, and serve it efficiently once you do.",
    "nodes": [
      {
        "title": "Decide: Fine-Tune, Prompt, or RAG?",
        "status": "live",
        "slug": "fine-tune-vs-prompt-vs-rag"
      },
      {
        "title": "Choose a Base Model to Fine-Tune",
        "status": "coming"
      },
      {
        "title": "Build a Fine-Tuning Dataset That Works",
        "status": "live",
        "slug": "building-a-fine-tuning-dataset"
      },
      {
        "title": "Generate Synthetic Training Data with a Larger Model",
        "status": "coming"
      },
      {
        "title": "Full Fine-Tuning vs Parameter-Efficient Fine-Tuning",
        "status": "coming"
      },
      {
        "title": "Fine-Tune with LoRA and QLoRA",
        "status": "live",
        "slug": "lora-and-qlora-fine-tuning"
      },
      {
        "title": "SFT vs Preference Tuning (DPO/RLHF)",
        "status": "coming"
      },
      {
        "title": "Set Hyperparameters for a Fine-Tuning Run",
        "status": "coming"
      },
      {
        "title": "Diagnose Catastrophic Forgetting and Overfitting",
        "status": "coming"
      },
      {
        "title": "Evaluate a Fine-Tuned Model Before Shipping",
        "status": "coming"
      },
      {
        "title": "Quantize a Model: GGUF, AWQ, and GPTQ",
        "status": "coming"
      },
      {
        "title": "Distill a Large Model into a Small One",
        "status": "coming"
      },
      {
        "title": "Optimize Inference Serving: Batching and KV Cache",
        "status": "coming"
      },
      {
        "title": "Merge and Version LoRA Adapters",
        "status": "coming"
      }
    ]
  }
];

export const roleTracks: RoleTrack[] = [
  {
    "id": "developer",
    "name": "Developer",
    "blurb": "Ship AI features that survive production, not just demos.",
    "status": "live"
  },
  {
    "id": "ml-engineer",
    "name": "ML Engineer",
    "blurb": "Go under the hood: train, fine-tune, and serve models efficiently.",
    "status": "live"
  },
  {
    "id": "data-scientist",
    "name": "Data Scientist",
    "blurb": "Turn LLMs into reliable tools for data work.",
    "status": "live"
  },
  {
    "id": "product-manager",
    "name": "Product Manager",
    "blurb": "Make sound calls on what to build with AI and what to avoid.",
    "status": "live"
  },
  {
    "id": "founder",
    "name": "Founder",
    "blurb": "Go from idea to a shipped, defensible AI product.",
    "status": "live"
  },
  {
    "id": "ceo",
    "name": "CEO",
    "blurb": "Understand AI deeply enough to steer strategy, not just slides.",
    "status": "live"
  },
  {
    "id": "designer",
    "name": "Designer",
    "blurb": "Design AI interactions that feel trustworthy, not magical or broken.",
    "status": "live"
  },
  {
    "id": "content-creator",
    "name": "Content Creator",
    "blurb": "Get consistent, high-quality output from models for creative work.",
    "status": "live"
  },
  {
    "id": "marketer",
    "name": "Marketer",
    "blurb": "Apply AI across content, research, and campaigns without getting burned.",
    "status": "live"
  },
  {
    "id": "security-engineer",
    "name": "Security Engineer",
    "blurb": "Find and fix the ways AI systems and agents get broken.",
    "status": "live"
  },
  {
    "id": "student",
    "name": "Student",
    "blurb": "Build a real foundation, from the maths up to working systems.",
    "status": "live"
  }
];

export function getTrack(id: string): Track | undefined { return tracks.find((t) => t.id === id); }
export const statusLabel: Record<NodeStatus, string> = { live: 'Live', curated: 'Curated', coming: 'Coming soon' };
